const excelColums = {
  cardExcel: [
    {
      name: '이용일시',
      required: true,
      label: '이용일시',
      align: 'left',
      style: 'width:100px',
      field: row => row.이용일시,
      format: val => `${val}`,
    },
    {
      name: '승인번호',
      required: true,
      label: '승인번호',
      align: 'left',
      style: 'width:100px',
      field: row => row.승인번호,
      format: val => `${val}`,
    },
    {
      name: '본인구분',
      required: true,
      label: '본인구분',
      align: 'left',
      style: 'width:100px',
      field: row => row.본인구분,
      format: val => `${val}`,
    },
    {
      name: '브랜드',
      required: true,
      label: '브랜드',
      align: 'left',
      style: 'width:100px',
      field: row => row.브랜드,
      format: val => `${val}`,
    },
    {
      name: '이용카드',
      required: true,
      label: '이용카드',
      align: 'left',
      style: 'width:100px',
      field: row => row.이용카드,
      format: val => `${val}`,
    },
    {
      name: '가맹점명',
      required: true,
      label: '가맹점명',
      align: 'left',
      style: 'width:100px',
      field: row => row.가맹점명,
      format: val => `${val}`,
    },
    {
      name: '이용금액',
      required: true,
      label: '이용금액',
      align: 'left',
      style: 'width:100px',
      field: row => row.이용금액,
      format: val => val.toLocaleString('ko-KR'),
    },
    {
      name: '이용구분',
      required: true,
      label: '이용구분',
      align: 'left',
      style: 'width:100px',
      field: row => row.이용구분,
      format: val => `${val}`,
    },
    {
      name: '매입상태',
      required: true,
      label: '매입상태',
      align: 'left',
      style: 'width:100px',
      field: row => row.매입상태,
      format: val => `${val}`,
    },
  ],
  bankExcel: [
    {
      name: '거래일자',
      required: true,
      label: '거래일자',
      align: 'left',
      style: 'width:100px',
      field: row => row.거래일자,
      format: val => `${val}`,
    },
    {
      name: '거래시간',
      required: true,
      label: '거래시간',
      align: 'left',
      style: 'width:100px',
      field: row => row.거래시간,
      format: val => `${val}`,
    },
    {
      name: '적요',
      required: true,
      label: '적요',
      align: 'left',
      style: 'width:100px',
      field: row => row.적요,
      format: val => `${val}`,
    },
    {
      name: '출금(원)',
      required: true,
      label: '출금(원)',
      align: 'left',
      style: 'width:100px',
      field: '출금(원)',
      format: val => val.toLocaleString('ko-KR'),
    },
    {
      name: '입금(원)',
      required: true,
      label: '입금(원)',
      align: 'left',
      style: 'width:100px',
      field: '입금(원)',
      format: val => val.toLocaleString('ko-KR'),
    },
    {
      name: '내용',
      required: true,
      label: '내용',
      align: 'left',
      style: 'width:100px',
      field: row => row.내용,
      format: val => `${val}`,
    },
    {
      name: '잔액(원)',
      required: true,
      label: '잔액(원)',
      align: 'left',
      style: 'width:100px',
      field: '잔액(원)',
      format: val => val.toLocaleString('ko-KR'),
    },
    {
      name: '거래점',
      required: true,
      label: '거래점',
      align: 'left',
      style: 'width:100px',
      field: row => row.거래점,
      format: val => `${val}`,
    },
  ],
};
export default excelColums;
